Feature/st lib (#6692)
* Minimal exports for app to consume + VerticalBlock and ElementNodeRenderer (#6623)

This PR is the first milestone to determine the minimal number of exports needed for app to consume + VerticalBlock + ElementNodeRenderer.

Most of the changes are import path changes. Some of the more notable changes to look through are

How the @streamlit/lib is built. It's built through the monorepo config for babel (https://babeljs.io/docs/config-files/#monorepos).
a. The babel process works by using a custom preset that is mainly babel-preset-react-app but slightly modified in order to make sure glide data grid code is es6 compatible and hard coding isTypeScriptEnabled to True.
b. The other keys are adding in the emotion plugin for styled-components, ignoring proto, vendor, test files, and telling babel that frontend is the root directory for babel config.
The actual index.ts that is added to frontend/lib
Some things to note that will be punt down but worked on later:

We also need to look into why protobuf can't be compiled through tsc.

Cleaning frontend/app/package.json
Cleaning frontend/app/yarn.lock
Cleaning frontend/lib/scripts/create.js
Determine what's going wrong with globalStyles typing
Determine what's going wrong with styled-components typing for EmotionTheme

* Change exports for protobuf to be included in index.ts instead of copied through cp command. (#6635)

Tim noticed that I was copying the protobuf.js and protobuf.d.ts instead of compiling it through babel. That causes problems because then you have to import by doing import { ... } from "@streamlit/lib/dist/proto" which doesn't make any sense.
The reason why I did that was because I was getting an error on first try:

`src/proto.js:4:1 - error TS9005: Declaration emit for this file requires using private name 'Radii'. An explicit type annotation may unblock declaration emit.

4 import * as $protobuf from "protobufjs/minimal";
  ~~~~~~

src/proto.js:4:1 - error TS9005: Declaration emit for this file requires using private name 'Radio'. An explicit type annotation may unblock declaration emit.

4 import * as $protobuf from "protobufjs/minimal";`
I just removed the proto files and did a make protobuf and then tried exporting and that worked, as it should.

* Simple fix for globalStyles (#6651)

* Fix typing issues for styled-components (#6652)

There are going to be 2 emotion.d.ts. Our @streamlit/lib has our own theming and then our app will simply just be consuming from @streamlit/lib which makes sense.

* remove extra app directory in frontend dir (#6653)

The current folder structure is frontend/app/src/app. We should make it so that it's frontend/app/src and remove the extra app directory.
This PR also fixes the audit_license script.

* Remove unnecessary files

* Fix naming of directories and files

* Fix BaseColorPicker directory

* Add Fixes that should exist in feature/st-lib

* Fix Eslint and Type-checking for st-lib (#6675)

This PR is to fix eslint for app and lib. This also adds dependencies that are necessary to lib's package.json. This is done through eslint noticing the necessary dependencies. This PR also does some linting and also does a merge from develop as we need the BaseButton refactoring to stop duplication of exports from the root index.ts.

In addition, this PR fixes the type checking github actions by adding new commands.

* Fix notices (#6676)

* Clean up audit_frontend_licenses

* Fix/yarn test (#6681)

This is to fix yarn test. This simply adds new scripts through the yarn workspace command to run app and lib tests.
Currently, the lib testing works by mainly using the same scripts that CRA uses for transpiling typescript to javascript.

There is one other thing to note: It looks like if you were to upgrade to 17.0.1 supposedly for react-dom, it would fix jest tests for app to not hang (facebook/react#20756 (comment)). However, jest was still hanging so I just did a delete MessageChannel within src/setupTests.js and we can remove that when we upgrade to React 18.

* Fix regex that I accidentally forgot to commit (#6698)

* Fix/cypress (#6699)

* Remove unused app dep / dev dep and declarations.d.ts (#6713)

* Remove unused app dep / dev dep and declarations.d.ts

* Remove d3 color resolution (#6714)

* Add dependencies removed from app to lib/package.json

* Add pbjs cli

* Readd notices

* Add watch lib script (#6730)

Since @streamlit/lib is separated out to be its own separate lib, we need a script to constantly rebuild when the files change.

Will also need to update the contributing wiki after this is merged to develop.

* Get rid of yarn start warnings and clean Makefile (#6739)

* Remove streamlit.css. I'm not sure where it came from

* Fix yarn buildLib

* Fix eslintrc

* Fix codeql

* Add notices and yarn.lock

* Fix glide-data-grid versions

* Fix nits

* Fix nits

* Lint and cleanup

* Minor cleanup for Block utils as comments got removed

* Remove accidentally committed file

* Revert "Remove accidentally committed file"

This reverts commit 87b7f13b9d872f2a39ecd4168fa79cdb33abe385.

* Fix yarn lock

* Fix compilation errors

* Fix lint

* Fix notices

* Remove unnecessary package.json dependencies

* Fix package.json versions

* Fix yarn.lock and streamlit dialog snapshots

* Fix notices

* Have faster hot reloading and absolute imports for @streamlit/lib (#6961)

<!--
⚠️ BEFORE CONTRIBUTING PLEASE READ OUR CONTRIBUTING GUIDELINES!
https://github.com/streamlit/streamlit/wiki/Contributing
-->

## Describe your changes
- Change imports for `app` to `@streamlit/app/src...` as we removed the `ModuleScopePlugin` which allows us to import out of `app/src`. 
- Change imports for `lib` to absolute imports
- add `tsconfig.dev.json` that is specifically for developement
- change `tsconfig.json` for `lib` and `app`
- change `.eslintrc` to `.eslintrc.js` in order to gain access to `__dirname` to make typescript configs relative to each project

## GitHub Issue Link (if applicable)

## Testing Plan
Manually testing
- Explanation of why no additional tests are needed
- Unit Tests (JS and/or Python)
- E2E Tests
- Any manual testing needed?
yes

https://github.com/streamlit/streamlit/assets/16749069/cc0a5f96-f8cd-487b-b70e-6a4e5823f0e7


---

**Contribution License Agreement**

By submitting this pull request you agree that all contributions to this project are made under the Apache 2.0 license.

* Fix minor comments from Lukas